// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markFeedFetch.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markFeedFetch = `-- name: MarkFeedFetch :exec
UPDATE feeds
SET last_fetched_at = $2, updated_at = $2
WHERE id = $1
`

type MarkFeedFetchParams struct {
	ID            uuid.UUID
	LastFetchedAt sql.NullTime
}

func (q *Queries) MarkFeedFetch(ctx context.Context, arg MarkFeedFetchParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetch, arg.ID, arg.LastFetchedAt)
	return err
}
