// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updatePost.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET updated_at = $2, title = $3, description = $4
WHERE id = $1
`

type UpdatePostParams struct {
	ID          uuid.UUID
	UpdatedAt   time.Time
	Title       sql.NullString
	Description sql.NullString
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.ID,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
	)
	return err
}
